# Site wide configuration

title:            Yellow Wall
locale:           en_US
url:              http://jekyll-dkris.rhcloud.com/


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Dhruva Krishnan
  avatar: blog_bio.jpg
  bio: "Front-end Engineer | UX Enthusiast | DJ | Diver | Craft Beer Lover"
  email: 
  disqus-shortname: 
  twitter: dkris
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: dkris
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: dkris
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
